//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-20051113-fcs 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2005.11.16 um 11:03:34 CET 
//


package phex.xml;


/**
 * Java content class for XJBFavoriteHost complex type.
 * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/projects/sourceforge/phex-project/trunk/phex/src/phex/xml/phex.xsd line 621)
 * <p>
 * <pre>
 * &lt;complexType name="XJBFavoriteHost">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="host-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ip" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *         &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface XJBFavoriteHost {


    /**
     * Gets the value of the ip property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    byte[] getIp();

    /**
     * Sets the value of the ip property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    void setIp(byte[] value);

    /**
     * Gets the value of the hostName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getHostName();

    /**
     * Sets the value of the hostName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setHostName(java.lang.String value);

    /**
     * Gets the value of the port property.
     * 
     */
    int getPort();

    /**
     * Sets the value of the port property.
     * 
     */
    void setPort(int value);

}
