//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-20051113-fcs 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2005.11.16 um 11:03:34 CET 
//


package phex.xml;


/**
 * Java content class for XJBGUISettings complex type.
 * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/projects/sourceforge/phex-project/trunk/phex/src/phex/xml/phex.xsd line 139)
 * <p>
 * <pre>
 * &lt;complexType name="XJBGUISettings">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="look-and-feel-class" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="is-toolbar-visible" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="is-log-bandwidth-slider-used" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="show-respect-copyright-notice" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="window-posX" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="window-posY" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="window-width" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="window-height" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="tab" type="{}XJBGUITab" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="table-list" type="{}XJBGUITableList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface XJBGUISettings {


    /**
     * Gets the value of the respectCopyrightNoticeShown property.
     * 
     */
    boolean isRespectCopyrightNoticeShown();

    /**
     * Sets the value of the respectCopyrightNoticeShown property.
     * 
     */
    void setRespectCopyrightNoticeShown(boolean value);

    boolean isSetRespectCopyrightNoticeShown();

    void unsetRespectCopyrightNoticeShown();

    /**
     * Gets the value of the windowPosX property.
     * 
     */
    int getWindowPosX();

    /**
     * Sets the value of the windowPosX property.
     * 
     */
    void setWindowPosX(int value);

    boolean isSetWindowPosX();

    void unsetWindowPosX();

    /**
     * Gets the value of the windowWidth property.
     * 
     */
    int getWindowWidth();

    /**
     * Sets the value of the windowWidth property.
     * 
     */
    void setWindowWidth(int value);

    boolean isSetWindowWidth();

    void unsetWindowWidth();

    /**
     * Gets the value of the lookAndFeelClass property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getLookAndFeelClass();

    /**
     * Sets the value of the lookAndFeelClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setLookAndFeelClass(java.lang.String value);

    /**
     * Gets the value of the logBandwidthSliderUsed property.
     * 
     */
    boolean isLogBandwidthSliderUsed();

    /**
     * Sets the value of the logBandwidthSliderUsed property.
     * 
     */
    void setLogBandwidthSliderUsed(boolean value);

    boolean isSetLogBandwidthSliderUsed();

    void unsetLogBandwidthSliderUsed();

    /**
     * Gets the value of the windowHeight property.
     * 
     */
    int getWindowHeight();

    /**
     * Sets the value of the windowHeight property.
     * 
     */
    void setWindowHeight(int value);

    boolean isSetWindowHeight();

    void unsetWindowHeight();

    /**
     * Gets the value of the tableList property.
     * 
     * @return
     *     possible object is
     *     {@link phex.xml.XJBGUITableList}
     */
    phex.xml.XJBGUITableList getTableList();

    /**
     * Sets the value of the tableList property.
     * 
     * @param value
     *     allowed object is
     *     {@link phex.xml.XJBGUITableList}
     */
    void setTableList(phex.xml.XJBGUITableList value);

    /**
     * Gets the value of the TabList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the TabList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTabList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link phex.xml.XJBGUITab}
     * 
     */
    java.util.List getTabList();

    /**
     * Gets the value of the windowPosY property.
     * 
     */
    int getWindowPosY();

    /**
     * Sets the value of the windowPosY property.
     * 
     */
    void setWindowPosY(int value);

    boolean isSetWindowPosY();

    void unsetWindowPosY();

    /**
     * Gets the value of the toolbarVisible property.
     * 
     */
    boolean isToolbarVisible();

    /**
     * Sets the value of the toolbarVisible property.
     * 
     */
    void setToolbarVisible(boolean value);

    boolean isSetToolbarVisible();

    void unsetToolbarVisible();

}
