//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-20051113-fcs 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2005.11.16 um 11:03:34 CET 
//


package phex.xml;


/**
 * Java content class for XJBIPAccessRule complex type.
 * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/projects/sourceforge/phex-project/trunk/phex/src/phex/xml/phex.xsd line 599)
 * <p>
 * <pre>
 * &lt;complexType name="XJBIPAccessRule">
 *   &lt;complexContent>
 *     &lt;extension base="{}XJBSecurityRule">
 *       &lt;sequence>
 *         &lt;element name="addressType" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *         &lt;element name="ip" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *         &lt;element name="compareIP" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface XJBIPAccessRule
    extends phex.xml.XJBSecurityRule
{


    /**
     * Gets the value of the compareIP property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    byte[] getCompareIP();

    /**
     * Sets the value of the compareIP property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    void setCompareIP(byte[] value);

    /**
     * Gets the value of the ip property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    byte[] getIp();

    /**
     * Sets the value of the ip property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    void setIp(byte[] value);

    /**
     * Gets the value of the addressType property.
     * 
     */
    byte getAddressType();

    /**
     * Sets the value of the addressType property.
     * 
     */
    void setAddressType(byte value);

}
