//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-20051113-fcs 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2005.11.16 um 11:03:34 CET 
//


package phex.xml;


/**
 * Java content class for XJBMediaType.
 *  <p>The following schema fragment specifies the expected 	content contained within this java content object.
 * <p>
 * <pre>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *   &lt;enumeration value="any"/>
 *   &lt;enumeration value="audio"/>
 *   &lt;enumeration value="video"/>
 *   &lt;enumeration value="program"/>
 * &lt;/restriction>
 * </pre>
 * 
 */
public class XJBMediaType {

    private final static java.util.Map valueMap = new java.util.HashMap();
    public final static java.lang.String _ANY = com.sun.xml.bind.DatatypeConverterImpl.installHook("any");
    public final static phex.xml.XJBMediaType ANY = new phex.xml.XJBMediaType(_ANY);
    public final static java.lang.String _AUDIO = com.sun.xml.bind.DatatypeConverterImpl.installHook("audio");
    public final static phex.xml.XJBMediaType AUDIO = new phex.xml.XJBMediaType(_AUDIO);
    public final static java.lang.String _VIDEO = com.sun.xml.bind.DatatypeConverterImpl.installHook("video");
    public final static phex.xml.XJBMediaType VIDEO = new phex.xml.XJBMediaType(_VIDEO);
    public final static java.lang.String _PROGRAM = com.sun.xml.bind.DatatypeConverterImpl.installHook("program");
    public final static phex.xml.XJBMediaType PROGRAM = new phex.xml.XJBMediaType(_PROGRAM);
    private final java.lang.String lexicalValue;
    private final java.lang.String value;

    protected XJBMediaType(java.lang.String v) {
        value = v;
        lexicalValue = v;
        valueMap.put(v, this);
    }

    public java.lang.String toString() {
        return lexicalValue;
    }

    public java.lang.String getValue() {
        return value;
    }

    public final int hashCode() {
        return super.hashCode();
    }

    public final boolean equals(java.lang.Object o) {
        return super.equals(o);
    }

    public static phex.xml.XJBMediaType fromValue(java.lang.String value) {
        phex.xml.XJBMediaType t = ((phex.xml.XJBMediaType) valueMap.get(value));
        if (t == null) {
            throw new java.lang.IllegalArgumentException();
        } else {
            return t;
        }
    }

    public static phex.xml.XJBMediaType fromString(java.lang.String str) {
        return fromValue(str);
    }

}
