//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-20051113-fcs 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2005.11.16 um 11:03:34 CET 
//


package phex.xml;


/**
 * Java content class for XJBPhex complex type.
 * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/projects/sourceforge/phex-project/trunk/phex/src/phex/xml/phex.xsd line 21)
 * <p>
 * <pre>
 * &lt;complexType name="XJBPhex">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="search-filters" type="{}XJBSearchFilters" minOccurs="0"/>
 *         &lt;element name="gui-settings" type="{}XJBGUISettings" minOccurs="0"/>
 *         &lt;element name="sharedLibrary" type="{}XJBSharedLibrary" minOccurs="0"/>
 *         &lt;element name="update-request" type="{}XJBUpdateRequest" minOccurs="0"/>
 *         &lt;element name="update-response" type="{}XJBUpdateResponse" minOccurs="0"/>
 *         &lt;element name="swDownloadList" type="{}XJBSWDownloadList" minOccurs="0"/>
 *         &lt;element name="security" type="{}XJBSecurity" minOccurs="0"/>
 *         &lt;element name="favorites-list" type="{}XJBFavoritesList" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="phex-version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface XJBPhex {


    /**
     * Gets the value of the swDownloadList property.
     * 
     * @return
     *     possible object is
     *     {@link phex.xml.XJBSWDownloadList}
     */
    phex.xml.XJBSWDownloadList getSWDownloadList();

    /**
     * Sets the value of the swDownloadList property.
     * 
     * @param value
     *     allowed object is
     *     {@link phex.xml.XJBSWDownloadList}
     */
    void setSWDownloadList(phex.xml.XJBSWDownloadList value);

    /**
     * Gets the value of the security property.
     * 
     * @return
     *     possible object is
     *     {@link phex.xml.XJBSecurity}
     */
    phex.xml.XJBSecurity getSecurity();

    /**
     * Sets the value of the security property.
     * 
     * @param value
     *     allowed object is
     *     {@link phex.xml.XJBSecurity}
     */
    void setSecurity(phex.xml.XJBSecurity value);

    /**
     * Gets the value of the updateRequest property.
     * 
     * @return
     *     possible object is
     *     {@link phex.xml.XJBUpdateRequest}
     */
    phex.xml.XJBUpdateRequest getUpdateRequest();

    /**
     * Sets the value of the updateRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link phex.xml.XJBUpdateRequest}
     */
    void setUpdateRequest(phex.xml.XJBUpdateRequest value);

    /**
     * Gets the value of the searchFilters property.
     * 
     * @return
     *     possible object is
     *     {@link phex.xml.XJBSearchFilters}
     */
    phex.xml.XJBSearchFilters getSearchFilters();

    /**
     * Sets the value of the searchFilters property.
     * 
     * @param value
     *     allowed object is
     *     {@link phex.xml.XJBSearchFilters}
     */
    void setSearchFilters(phex.xml.XJBSearchFilters value);

    /**
     * Gets the value of the phexVersion property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getPhexVersion();

    /**
     * Sets the value of the phexVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setPhexVersion(java.lang.String value);

    /**
     * Gets the value of the updateResponse property.
     * 
     * @return
     *     possible object is
     *     {@link phex.xml.XJBUpdateResponse}
     */
    phex.xml.XJBUpdateResponse getUpdateResponse();

    /**
     * Sets the value of the updateResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link phex.xml.XJBUpdateResponse}
     */
    void setUpdateResponse(phex.xml.XJBUpdateResponse value);

    /**
     * Gets the value of the favoritesList property.
     * 
     * @return
     *     possible object is
     *     {@link phex.xml.XJBFavoritesList}
     */
    phex.xml.XJBFavoritesList getFavoritesList();

    /**
     * Sets the value of the favoritesList property.
     * 
     * @param value
     *     allowed object is
     *     {@link phex.xml.XJBFavoritesList}
     */
    void setFavoritesList(phex.xml.XJBFavoritesList value);

    /**
     * Gets the value of the sharedLibrary property.
     * 
     * @return
     *     possible object is
     *     {@link phex.xml.XJBSharedLibrary}
     */
    phex.xml.XJBSharedLibrary getSharedLibrary();

    /**
     * Sets the value of the sharedLibrary property.
     * 
     * @param value
     *     allowed object is
     *     {@link phex.xml.XJBSharedLibrary}
     */
    void setSharedLibrary(phex.xml.XJBSharedLibrary value);

    /**
     * Gets the value of the guiSettings property.
     * 
     * @return
     *     possible object is
     *     {@link phex.xml.XJBGUISettings}
     */
    phex.xml.XJBGUISettings getGuiSettings();

    /**
     * Sets the value of the guiSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link phex.xml.XJBGUISettings}
     */
    void setGuiSettings(phex.xml.XJBGUISettings value);

}
