//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-20051113-fcs 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2005.11.16 um 11:03:34 CET 
//


package phex.xml;


/**
 * Java content class for XJBSecurityRule complex type.
 * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/projects/sourceforge/phex-project/trunk/phex/src/phex/xml/phex.xsd line 564)
 * <p>
 * <pre>
 * &lt;complexType name="XJBSecurityRule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isDenyingRule" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isDisabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isSystemRule" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="triggerCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="expiryDate" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="isDeletedOnExpiry" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface XJBSecurityRule {


    /**
     * Gets the value of the triggerCount property.
     * 
     */
    int getTriggerCount();

    /**
     * Sets the value of the triggerCount property.
     * 
     */
    void setTriggerCount(int value);

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getDescription();

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setDescription(java.lang.String value);

    /**
     * Gets the value of the denyingRule property.
     * 
     */
    boolean isDenyingRule();

    /**
     * Sets the value of the denyingRule property.
     * 
     */
    void setDenyingRule(boolean value);

    /**
     * Gets the value of the expiryDate property.
     * 
     */
    long getExpiryDate();

    /**
     * Sets the value of the expiryDate property.
     * 
     */
    void setExpiryDate(long value);

    /**
     * Gets the value of the systemRule property.
     * 
     */
    boolean isSystemRule();

    /**
     * Sets the value of the systemRule property.
     * 
     */
    void setSystemRule(boolean value);

    /**
     * Gets the value of the disabled property.
     * 
     */
    boolean isDisabled();

    /**
     * Sets the value of the disabled property.
     * 
     */
    void setDisabled(boolean value);

    /**
     * Gets the value of the deletedOnExpiry property.
     * 
     */
    boolean isDeletedOnExpiry();

    /**
     * Sets the value of the deletedOnExpiry property.
     * 
     */
    void setDeletedOnExpiry(boolean value);

}
