//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-20051113-fcs 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2005.11.16 um 11:03:34 CET 
//


package phex.xml;


/**
 * @deprecated since Phex 2.6.5.90 use XJBDownloadScope
 * 
 * Java content class for XJBSWDownloadSegment complex type.
 * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/projects/sourceforge/phex-project/trunk/phex/src/phex/xml/phex.xsd line 525)
 * <p>
 * <pre>
 * &lt;complexType name="XJBSWDownloadSegment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="incompleteFileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="segmentNumber" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="startPosition" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="length" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="transferred" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface XJBSWDownloadSegment {


    /**
     * Gets the value of the transferred property.
     * 
     */
    long getTransferred();

    /**
     * Sets the value of the transferred property.
     * 
     */
    void setTransferred(long value);

    /**
     * Gets the value of the length property.
     * 
     */
    long getLength();

    /**
     * Sets the value of the length property.
     * 
     */
    void setLength(long value);

    /**
     * Gets the value of the incompleteFileName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIncompleteFileName();

    /**
     * Sets the value of the incompleteFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIncompleteFileName(java.lang.String value);

    /**
     * Gets the value of the startPosition property.
     * 
     */
    long getStartPosition();

    /**
     * Sets the value of the startPosition property.
     * 
     */
    void setStartPosition(long value);

    /**
     * Gets the value of the segmentNumber property.
     * 
     */
    int getSegmentNumber();

    /**
     * Sets the value of the segmentNumber property.
     * 
     */
    void setSegmentNumber(int value);

}
