//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-20051113-fcs 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2005.11.16 um 11:03:34 CET 
//


package phex.xml;


/**
 * Java content class for XJBSWDownloadCandidate complex type.
 * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/projects/sourceforge/phex-project/trunk/phex/src/phex/xml/phex.xsd line 441)
 * <p>
 * <pre>
 * &lt;complexType name="XJBSWDownloadCandidate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fileindex" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="last-connect" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="download-uri" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="remotehost" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="connectionFailedRepetition" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="rating" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
 *         &lt;element name="vendor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isPushNeeded" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isThexSupported" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isChatSupported" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface XJBSWDownloadCandidate {


    /**
     * Gets the value of the remoteHost property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getRemoteHost();

    /**
     * Sets the value of the remoteHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setRemoteHost(java.lang.String value);

    /**
     * Gets the value of the thexSupported property.
     * 
     */
    boolean isThexSupported();

    /**
     * Sets the value of the thexSupported property.
     * 
     */
    void setThexSupported(boolean value);

    /**
     * Gets the value of the connectionFailedRepetition property.
     * 
     */
    int getConnectionFailedRepetition();

    /**
     * Sets the value of the connectionFailedRepetition property.
     * 
     */
    void setConnectionFailedRepetition(int value);

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getGUID();

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setGUID(java.lang.String value);

    /**
     * Gets the value of the lastConnectionTime property.
     * 
     */
    long getLastConnectionTime();

    /**
     * Sets the value of the lastConnectionTime property.
     * 
     */
    void setLastConnectionTime(long value);

    boolean isSetLastConnectionTime();

    void unsetLastConnectionTime();

    /**
     * Gets the value of the pushNeeded property.
     * 
     */
    boolean isPushNeeded();

    /**
     * Sets the value of the pushNeeded property.
     * 
     */
    void setPushNeeded(boolean value);

    /**
     * Gets the value of the downloadURI property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getDownloadURI();

    /**
     * Sets the value of the downloadURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setDownloadURI(java.lang.String value);

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getFileName();

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setFileName(java.lang.String value);

    /**
     * Gets the value of the fileIndex property.
     * 
     */
    long getFileIndex();

    /**
     * Sets the value of the fileIndex property.
     * 
     */
    void setFileIndex(long value);

    /**
     * Gets the value of the rating property.
     * 
     * @return
     *     possible object is
     *     {@link phex.xml.XJBSWDownloadCandidate.RatingElement}
     */
    phex.xml.XJBSWDownloadCandidate.RatingElement getRating();

    /**
     * Sets the value of the rating property.
     * 
     * @param value
     *     allowed object is
     *     {@link phex.xml.XJBSWDownloadCandidate.RatingElement}
     */
    void setRating(phex.xml.XJBSWDownloadCandidate.RatingElement value);

    /**
     * Gets the value of the chatSupported property.
     * 
     */
    boolean isChatSupported();

    /**
     * Sets the value of the chatSupported property.
     * 
     */
    void setChatSupported(boolean value);

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getVendor();

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setVendor(java.lang.String value);


    /**
     * @deprecated since Phex 2.6.5.90. The field is only still
     * here because JAXB cant ignore unknown elements and we like to be able to update
     * from old releases.
     * 
     * Java content class for rating element declaration.
     * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/projects/sourceforge/phex-project/trunk/phex/src/phex/xml/phex.xsd line 486)
     * <p>
     * <pre>
     * &lt;element name="rating" type="{http://www.w3.org/2001/XMLSchema}short"/>
     * </pre>
     * 
     */
    public interface RatingElement
        extends javax.xml.bind.Element
    {


        /**
         * Gets the value of the value property.
         * 
         */
        short getValue();

        /**
         * Sets the value of the value property.
         * 
         */
        void setValue(short value);

    }

}
