//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-20051113-fcs 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2005.11.16 um 11:03:34 CET 
//


package phex.xml;


/**
 * Java content class for XJBSharedFile complex type.
 * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/projects/sourceforge/phex-project/trunk/phex/src/phex/xml/phex.xsd line 286)
 * <p>
 * <pre>
 * &lt;complexType name="XJBSharedFile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SHA1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TxRH" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TxD" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="TxLLN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LM" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="LS" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="HC" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="UC" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="AltLoc" type="{}XJBAlternateLocation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface XJBSharedFile {


    /**
     * Gets the value of the lastModified property.
     * 
     */
    long getLastModified();

    /**
     * Sets the value of the lastModified property.
     * 
     */
    void setLastModified(long value);

    /**
     * Gets the value of the hitCount property.
     * 
     */
    int getHitCount();

    /**
     * Sets the value of the hitCount property.
     * 
     */
    void setHitCount(int value);

    /**
     * Gets the value of the sha1 property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getSHA1();

    /**
     * Sets the value of the sha1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setSHA1(java.lang.String value);

    /**
     * Gets the value of the thexLowestLevelNodes property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getThexLowestLevelNodes();

    /**
     * Sets the value of the thexLowestLevelNodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setThexLowestLevelNodes(java.lang.String value);

    /**
     * Gets the value of the thexRootHash property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getThexRootHash();

    /**
     * Sets the value of the thexRootHash property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setThexRootHash(java.lang.String value);

    /**
     * Gets the value of the lastSeen property.
     * 
     */
    int getLastSeen();

    /**
     * Sets the value of the lastSeen property.
     * 
     */
    void setLastSeen(int value);

    /**
     * Gets the value of the thexTreeDepth property.
     * 
     */
    int getThexTreeDepth();

    /**
     * Sets the value of the thexTreeDepth property.
     * 
     */
    void setThexTreeDepth(int value);

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getFileName();

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setFileName(java.lang.String value);

    /**
     * Gets the value of the AltLoc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the AltLoc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAltLoc().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link phex.xml.XJBAlternateLocation}
     * 
     */
    java.util.List getAltLoc();

    /**
     * Gets the value of the uploadCount property.
     * 
     */
    int getUploadCount();

    /**
     * Sets the value of the uploadCount property.
     * 
     */
    void setUploadCount(int value);

}
